server: # 服务器配置
  httpPort: 8080  # 端口号
  systemName: 5z7game # 系统名称
  maxResponseLogSize: 2000 # 响应内容截取长度
  logPath: /tmp/app.log # 日志文件
  traceHeader: gateway-trace # trace头
  httpRequestTimeout: 3 # http请求超时时间，单位：秒
  jwtSign: 5z7-sign  # jwt的签名
  debug: true # 日志debug

mysql:    # mysql配置。支持多数据库，读写分离
  default:  # 默认连接，如果还有其他数据库要连接，换个名字即可
    maxIdleConnections: 10  # 最大空闲连接数
    maxOpenConnections: 40  # 最大打开连接数
    maxLifeTime: 8          # 超时时间
    dsn:    # 连接配置，默认第一个为写库，也可以只配置一个，即读写使用一个连接
      - host: 127.0.0.1
        port: 3306
        user: root
        password:
        name: wuziqi
#db:
#  driver: mysql
#  dbNameKey: wuziqi
#  dbHostKey: 127.0.0.1
#  dbPortKey: 3306
#  dbUserKey: admin
#  dbPassKey: 123456
#
#redis: